### ISSUE TITLE
[Blacklist] Malware apps from Android

### ISSUE THREAD

**Issue by SaberAkiyama** [Ultimate-Hosts-Blacklist/blacklist#4]
List of malware sites:

```
clock.via.net
hshh.org
boot.b7cc213c6.net
www.itinerantponytail.com
www.e552a2d7dcb1bccf20ae908b3c71e59c.top
www.72f46511412cb5b7153d836c6d3e0596.top
www.ac745fed2a5195d367c5fa089cbf6935.top
www.6c982595fcee64ebb60e7e974f7d1bbd.top
www.4903526a67a3bba64deb43443cef4f7a.top
www.48411185c3925d931936dac75dbc4e2f.top
www.9190ed6851889dba3bd6251d2eb8c0d0.top
www.246d9f6f248262eeca640e9f461d1b14.top
www.050f634043855a15c23531bc97c9b3bd.top
www.a0c8b03884bd5d3b977e296c81f7b667.top
www.aabaef3c49452b269944e6e23448cd5a.top
www.5333911ddd5d433ae1c2d9f546b1f75b.top
www.dfd91296e9619edfcb7d64b09c65e1bf.top
www.d87e02bcc0bf488a12da060a25f5c1c8.top
www.44548a20c646a166e6fbf100119e2895.top
www.aef23a0ba9dc554942dd1322ddfbbf70.top
www.7b238984ea315992bb859b39c871b65c.top
www.2098007a060fc04a940f4a0cce76ebee.top
www.11b0980ab1d0466b8ed7863c91211c62.top
asia.pool.ntp.org
d1.bugreportsync.com
statistics.flurrydata.com
boot.b28e82a1d.net
www.ac2f261f95df2c0e7412a832d338ac95.top
qqq.xxpwgxx.com
www.bullishlifer.com
www.eternitynostalgia.com
www.cakgopfw892.com
wewjyw.qb6ges.com
cf.zcnewy.com
wscdn.xiaoshuzhan.net.whecloud.com
wscdn.xiaoshuzhan.net
vgl8ku.miccuu.com
cu.smaxdn.com
report.smaxdn.com
apply.smaxdn.com
tcq.xinfu300.com
ppp.xxpwgxx.com
```

**Comment by SaberAkiyama** [comment]
Hello?

**Comment by dnmTX** [comment]
@funilrys can we wildcard those: `www.e552a2d7dcb1bccf20ae908b3c71e59c.top` => `www.[ wildcard here ].top`
same goes for `*.smaxdn.com`  `*.xxpwgxx.com`
@SaberAkiyama  this is NO GO: 
`clock.via.net`
`hshh.org`
`asia.pool.ntp.org`
...do your due diligence first before you start listing everyithing that pops up in your logs !!!!!

**Comment by SaberAkiyama** [comment]
You should go to Virus Total website, copy those link, enter and remove ```http://*/```. You can see have a detection.

**Comment by dnmTX** [comment]
Those are **ntp servers** and are needed,the first one is is to sync the clock from that `via.net` server.
That's what i need to know,i can care less about detections.

**Comment by funilrys** [comment]
Also for more context about this @SaberAkiyama:

Virus Total uses for example one of our (@mitchellkrogza  and I ) sources [Phishing.Database](https://github.com/mitchellkrogza/Phishing.Database), meaning that they show you something base on our work/automation process. Meaning that you have to be aware of what the source is. Detection out here is what we care less about because, well VT uses some of our (@mitchellkrogza and I) projects. 

I have to second @dnmTX regarding NTP servers. They are used to synchronizes time and should never be blocked. 
But for those that are legit, we are going to see how we may include them. 

Just beware that Virus Total is less of a valid source within our scope, just because in "URL Detection", they use one of our sources. 

----

@dnmTX Wildcard should be possible indeed.

**Comment by SaberAkiyama** [comment]
@funilrys I know. But the issues has been closed, by the way. I guess I'm deleted my issue and do nothing.

**Comment by dnmTX** [comment]
@SaberAkiyama confirm that you want your issue to be removed from here.
